# Generated by Django 2.0.3 on 2018-03-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('crew', models.BooleanField(default=True)),
                ('talent', models.BooleanField(default=False)),
                ('producer', models.BooleanField(default=False)),
                ('serviceProvider', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
