# Generated by Django 2.0.3 on 2018-03-06 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSystem', '0003_user_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
