# Generated by Django 2.0.3 on 2018-03-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSystem', '0005_auto_20180307_0413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
