# Generated by Django 2.0.3 on 2018-03-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSystem', '0008_auto_20180307_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt',
            field=models.IntegerField(default=0),
        ),
    ]
